version: '3'

services:
  tensorflowapi:
    image: tensorflow/serving:latest
    restart: unless-stopped
    ports:
      - "8500:8500"
      - "8501:8501"
    command:
      - --enable_batching=true
      - --model_config_file_poll_wait_seconds=300
      - --rest_api_timeout_in_ms=30000
    volumes:
      - type: bind
        source: /home/jlcg/Projects/AI hackathon/models/serving_models/land-cover
        target: /models/land-cover
    environment:
      - MODEL_NAME=land-cover
      - MODEL_BASE=/models/land-cover
    networks:
      - backend
  api:
    container_name: api
    restart: always
    build: ./api
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b :8000 app:app
    depends_on:
      - tensorflow
    networks:
      - backend
      - frontend
  server:
    container_name: server_nginx
    restart: always
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - frontend
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge